/// Flutter icons MoyaMoyaIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoyaMoyaIcons
///      fonts:
///       - asset: fonts/MoyaMoyaIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MoyaMoyaIcons {
  MoyaMoyaIcons._();

  static const _kFontFam = 'MoyaMoyaIcons';
  static const String? _kFontPkg = null;

  static const IconData checkline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lefticon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData out = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnifyingglass = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
